site_name: Cjk CMS Docs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.path
markdown_extensions:
  - admonition
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true